### ISSUE TITLE
[Task] Learn about NVIDIA board

### ISSUE THREAD

**Issue by ziliolu** [SEAME-pt/WarmUp-Team02#87]
### Description

Understand how to set up NVIDIA board and program basic commands for testing. 

### Priority

High

### Story Reference

- #16

**Comment by luis-ffe** [comment]
# ✅ DONE  ✅ 

- [x] Research on the Nvidea Board
- [x] Assembled to the car and Documentation with specification found.
- [x] Tested Basic commans on the Board

- Further research needed.

### 🔒 CLOSED 🔒
